---
- name: Download node_exporter binary to local folder
  get_url:
    url: "{{ node_exporter_binary_url }}"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"

- name: Unpack node_exporter binary
  unarchive:
    remote_src: yes
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}.tar.gz"
    dest: "/tmp"

- name: Move node_exporter binaries
  copy:
    remote_src: yes
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ arch }}/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: 0755
    owner: root
    group: root
