- name: Install required packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - nano
    - wget
    - htop
    - git
  when: ansible_os_family == "RedHat"

- name: Install required packages
  apt:
    pkg: "{{ item }}"
  with_items:
    - nano
    - wget
    - htop
    - git
  when: ansible_os_family == "Debian"
